In [0]:
from google.colab import drive
drive.mount('/content/gdrive')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
cd gdrive/My Drive/Datasets/Titanic

/content/gdrive/My Drive/Datasets/Titanic


In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import keras
from sklearn.preprocessing import OneHotEncoder

In [0]:
train = pd.read_csv('train.csv')
train=train.drop(["PassengerId","Name","Ticket","Cabin"],axis=1)
train=pd.get_dummies(train, drop_first=True)
train.fillna( train.mean(), inplace = True)
print(train)
y_train=train["Survived"].values
x_train=train.drop(["Survived"],axis=1).values

     Survived  Pclass        Age  ...  Sex_male  Embarked_Q  Embarked_S
0           0       3  22.000000  ...         1           0           1
1           1       1  38.000000  ...         0           0           0
2           1       3  26.000000  ...         0           0           1
3           1       1  35.000000  ...         0           0           1
4           0       3  35.000000  ...         1           0           1
5           0       3  29.699118  ...         1           1           0
6           0       1  54.000000  ...         1           0           1
7           0       3   2.000000  ...         1           0           1
8           1       3  27.000000  ...         0           0           1
9           1       2  14.000000  ...         0           0           0
10          1       3   4.000000  ...         0           0           1
11          1       1  58.000000  ...         0           0           1
12          0       3  20.000000  ...         1           0     

In [0]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
x_train = onehotencoder.fit_transform(x_train).toarray()
x_train

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[0., 0., 1., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 1.],
       ...,
       [0., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [0]:
from sklearn.model_selection  import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size = 0.1, random_state = 0)


In [0]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(801, 10) (90, 10) (801,) (90,)


In [0]:
from sklearn.ensemble import RandomForestRegressor
classifier = RandomForestRegressor(n_estimators = 2)
classifier.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=2, n_jobs=None,
                      oob_score=False, random_state=None, verbose=0,
                      warm_start=False)

In [0]:
x_test.shape

(90, 10)

In [0]:
# from sklearn.preprocessing import OneHotEncoder
# onehotencoder = OneHotEncoder(categorical_features = [1])
# x_test = onehotencoder.fit_transform(x_test).toarray()
# x_test

In [0]:
x_test.shape

(90, 10)

In [0]:
y_pred = classifier.predict(x_test)

In [0]:
y_pred=y_pred>=0.5

In [0]:
y_pred

array([False, False, False,  True, False, False,  True,  True, False,
        True, False,  True, False,  True,  True,  True, False, False,
       False,  True, False,  True, False, False, False,  True, False,
        True,  True,  True, False,  True,  True, False, False, False,
       False, False, False, False, False,  True, False, False,  True,
       False, False,  True,  True, False, False,  True,  True, False,
       False, False, False, False,  True, False,  True,  True,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
       False, False, False,  True, False,  True, False, False, False,
        True,  True, False, False,  True,  True, False,  True, False])

In [0]:

y_test.shape

(90,)

In [0]:
y_pred.shape

(90,)

In [0]:
x_test.shape

(90, 10)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)


[[40 11]
 [11 28]]


In [0]:
test = pd.read_csv('test.csv')

In [0]:
test=test.drop(["PassengerId","Name","Ticket","Cabin"],axis=1)
test=pd.get_dummies(test, drop_first=True)
test.fillna( test.mean(), inplace = True)
x_test=test.values



In [0]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
x_test = onehotencoder.fit_transform(x_test).toarray()
x_test

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[0., 0., 1., ..., 1., 1., 0.],
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 1., 0., ..., 1., 1., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 1.],
       [0., 0., 1., ..., 1., 0., 1.],
       [0., 0., 1., ..., 1., 0., 0.]])

In [0]:
y_pred = classifier.predict(x_test)

In [0]:
y_pred=y_pred>=0.5

In [0]:
y_pred=pd.get_dummies(y_pred, drop_first=True)

In [0]:
y_pred

True
0       0
1       0
2       1
3       1
4       0
5       0
6       1
7       0
8       1
9       0
10      0
11      0
12      1
13      1
14      1
15      1
16      0
17      1
18      1
19      0
20      0
21      1
22      1
23      1
24      1
25      0
26      1
27      1
28      1
29      0
..    ...
388     0
389     0
390     0
391     1
392     1
393     0
394     0
395     1
396     0
397     1
398     0
399     0
400     1
401     0
402     1
403     1
404     1
405     0
406     0
407     0
408     1
409     1
410     0
411     1
412     1
413     0
414     1
415     0
416     0
417     1

[418 rows x 1 columns]

In [0]:
result=pd.read_csv('gender_submission.csv')

In [0]:
result=result.drop(["Survived"],axis=1)

In [0]:
result["Survived"]=y_pred

In [0]:
result

PassengerId  Survived
0            892         0
1            893         0
2            894         1
3            895         1
4            896         1
5            897         0
6            898         0
7            899         1
8            900         1
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         1
18           910         1
19           911         0
20           912         0
21           913         1
22           914         1
23           915         0
24           916         1
25           917         0
26           918         1
27           919         1
28           920         1
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         1
391         1283         1
392         1284         1
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         0
405         1297         0
406         1298         0
407         1299         1
408         1300         0
409         1301         1
410         1302         0
411         1303         1
412         1304         0
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [0]:
result.to_csv("result.csv", encoding='utf-8',index=False)

In [0]:
ls

gender_submission.csv  result.csv  test.csv  train.csv


In [0]:
f = pd.read_csv('result.csv')

In [0]:
f

PassengerId  Survived
0            892         0
1            893         0
2            894         1
3            895         1
4            896         1
5            897         0
6            898         0
7            899         1
8            900         1
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         1
18           910         1
19           911         0
20           912         0
21           913         1
22           914         1
23           915         0
24           916         1
25           917         0
26           918         1
27           919         1
28           920         1
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         1
391         1283         1
392         1284         1
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         0
405         1297         0
406         1298         0
407         1299         1
408         1300         0
409         1301         1
410         1302         0
411         1303         1
412         1304         0
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]